In [9]:
import pandas as pd
import numpy as np

In [ ]:
crop_rec = pd.read_csv('crop_recommendation_unida.csv')
crop_rec.head()

,id,N,P,K,temperature,humidity,ph,rainfall,crop,crop_code,depto_code,id_depto,departamento_colombia,zona_vida,temperature_min,temperature_max,rainfall_min,rainfall_max,Longitud,Latitud
0,1,90,42,43,2.087.974.371,8.200.274.423,6.502.985.292.000.000,2.029.355.362,rice,1,1,1,Casanare,Bosque Humedo-Tropical,20.0,33.0,1000.0,2500.0,"-71,60188121","5,404063946"
1,2,85,58,41,2.177.046.169,8.031.964.408,7.038.096.361,2.266.555.374,rice,1,1,1,Casanare,Bosque Humedo-Tropical,20.0,33.0,1000.0,2500.0,"-71,60188121","5,404063946"
2,3,60,55,44,2.300.445.915,823.207.629,7.840.207.144,2.639.642.476,rice,1,1,1,Casanare,Bosque Humedo-Tropical,20.0,33.0,1000.0,2500.0,"-71,60188121","5,404063946"
3,4,74,35,40,2.649.109.635,8.015.836.264,6.980.400.905,2.428.640.342,rice,1,1,1,Casanare,Bosque Humedo-Tropical,20.0,33.0,1000.0,2500.0,"-71,60188121","5,404063946"
4,5,78,42,42,2.013.017.482,8.160.487.287,7.628.472.891,2.627.173.405,rice,1,1,1,Casanare,Bosque Humedo-Tropical,20.0,33.0,1000.0,2500.0,"-71,60188121","5,404063946"

In [11]:
ensayo = crop_rec.copy()

In [12]:
def add_char_index(cadena, char = '.', i = 0, remove_char = False):
    if remove_char == True:
        cadena = str(cadena.replace(char, ''))
    left = cadena[:i]
    right = cadena[i:]
    return float(left + char + right)

In [13]:
ensayo['temperature'] = ensayo['temperature'].apply(lambda x: add_char_index(x, '.', 2, True))
ensayo['humidity'] = ensayo['humidity'].apply(lambda x: add_char_index(x, '.', 2, True))
ensayo['ph'] = ensayo['ph'].apply(lambda x: add_char_index(x, '.', 1, True))
ensayo['rainfall'] = ensayo['rainfall'].apply(lambda x: add_char_index(x, '.', 3, True))

ensayo.head()

,id,N,P,K,temperature,humidity,ph,rainfall,crop,crop_code,depto_code,id_depto,departamento_colombia,zona_vida,temperature_min,temperature_max,rainfall_min,rainfall_max,Longitud,Latitud
0,1,90,42,43,20.879744,82.002744,6.502985,202.935536,rice,1,1,1,Casanare,Bosque Humedo-Tropical,20.0,33.0,1000.0,2500.0,"-71,60188121","5,404063946"
1,2,85,58,41,21.770462,80.319644,7.038096,226.655537,rice,1,1,1,Casanare,Bosque Humedo-Tropical,20.0,33.0,1000.0,2500.0,"-71,60188121","5,404063946"
2,3,60,55,44,23.004459,82.320763,7.840207,263.964248,rice,1,1,1,Casanare,Bosque Humedo-Tropical,20.0,33.0,1000.0,2500.0,"-71,60188121","5,404063946"
3,4,74,35,40,26.491096,80.158363,6.980401,242.864034,rice,1,1,1,Casanare,Bosque Humedo-Tropical,20.0,33.0,1000.0,2500.0,"-71,60188121","5,404063946"
4,5,78,42,42,20.130175,81.604873,7.628473,262.717340,rice,1,1,1,Casanare,Bosque Humedo-Tropical,20.0,33.0,1000.0,2500.0,"-71,60188121","5,404063946"

In [14]:
columnas = ['temperature', 'humidity', 'ph', 'rainfall']
ensayo[columnas] = ensayo[columnas].round(3)
ensayo.head()

,id,N,P,K,temperature,humidity,ph,rainfall,crop,crop_code,depto_code,id_depto,departamento_colombia,zona_vida,temperature_min,temperature_max,rainfall_min,rainfall_max,Longitud,Latitud
0,1,90,42,43,20.880,82.003,6.503,202.936,rice,1,1,1,Casanare,Bosque Humedo-Tropical,20.0,33.0,1000.0,2500.0,"-71,60188121","5,404063946"
1,2,85,58,41,21.770,80.320,7.038,226.656,rice,1,1,1,Casanare,Bosque Humedo-Tropical,20.0,33.0,1000.0,2500.0,"-71,60188121","5,404063946"
2,3,60,55,44,23.004,82.321,7.840,263.964,rice,1,1,1,Casanare,Bosque Humedo-Tropical,20.0,33.0,1000.0,2500.0,"-71,60188121","5,404063946"
3,4,74,35,40,26.491,80.158,6.980,242.864,rice,1,1,1,Casanare,Bosque Humedo-Tropical,20.0,33.0,1000.0,2500.0,"-71,60188121","5,404063946"
4,5,78,42,42,20.130,81.605,7.628,262.717,rice,1,1,1,Casanare,Bosque Humedo-Tropical,20.0,33.0,1000.0,2500.0,"-71,60188121","5,404063946"

In [ ]:
ensayo.to_excel('crop_recommendation_corregida.xlsx')